nguage: ruby
script: bundle exec rake test test:isolated test:integration
cache:  bundler
sudo:   false

before_install:
  - gem install bundler
  - openssl aes-256-cbc -K $encrypted_86ed69f44076_key -iv $encrypted_86ed69f44076_iv -in ./certs/apns_auth_key_for_jwt_auth.p8.enc -out certs/apns_auth_key_for_jwt_auth.p8 -d
  - openssl aes-256-cbc -K $encrypted_86ed69f44076_key -iv $encrypted_86ed69f44076_iv -in ./certs/apns_example_production.pem.enc -out certs/apns_example_production.pem -d

rvm:
  - 2.2.10
  - 2.3.8
  - 2.4.5
  - 2.5.3
  - 2.6.1
  - ruby-head
  - jruby-9.2.6.0
  - jruby-head

gemfile:
  - gemfiles/rails_42.gemfile
  - gemfiles/rails_50.gemfile
  - gemfiles/rails_51.gemfile
  - gemfiles/rails_52.gemfile
  - gemfiles/rails_edge.gemfile

matrix:
  allow_failures:
    - rvm: ruby-head
    - rvm: jruby-9.2.6.0
    - rvm: jruby-head
    - gemfile: gemfiles/rails_edge.gemfile
  exclude:
    - rvm: 2.4.5
      gemfile: gemfiles/rails_edge.gemfile
    - rvm: 2.3.8
      gemfile: gemfiles/rails_edge.gemfile
    - rvm: 2.2.10
      gemfile: gemfiles/rails_52.gemfile
    - rvm: 2.2.10
      gemfile: gemfiles/rails_edge.gemfile
